//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_stok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_satislar
    {
        public int satis_id { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual tbl_musteriler tbl_musteriler { get; set; }
        public virtual tbl_urunler tbl_urunler { get; set; }
    }
}
